import "@/styles/globals.css"
import { cn } from "@/lib/utils"
import Navbar from "@/components/Navbar"
import Providers from "@/components/Providers"
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { buttonVariants } from '@/ui/Button'
import Pwa from "@/components/Pwa"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn(
        "bg-slate-300 antialiased", inter.className
      )}>
      <head>
        <link rel="manifest" href="./manifest.json" />
        <link rel="apple-touch-icon" href="/icon.png"></link>
        <meta name="theme-color" content="#fff" />
      </head>
      <body className="min-h-screen bg-slate-300 dark:bg-slate-900 antialiased">
        <Providers>
          <Navbar/>
          {children}
        </Providers>

        <div className="fixed bottom-0 mb-20 md:hidden min-w-full flex justify-center ">
          <Link className={buttonVariants({variant: "link"})} href="/"> Documentation</Link>
          <Link className={buttonVariants({variant: "default"})} href="/"> Logs</Link>
        </div>
      </body>
    </html>
  )
}
